### ISSUE TITLE
სიმულატორი, დასაწერი

### ISSUE THREAD

**Issue by Rshalika** [freeuni-sdp/iot-bath-vent-switch#1]
სიმულატორზე ერთად უნდა ვიმუშაოთ წესით. შევთანხმდეთ რაღაცებზე

iot-bath-climate team here

**Comment by ghost** [comment]
ძალიან კარგი, შევთანხმდეთ.

**Comment by gosip** [comment]
iot-sim-bath-ში შევთანხმეთ ბარემ ყველა ერთად.
